=== navikt/dokdistsentralprint/schemas/src/main/resources/no/nav/dokdistsentralprint/printoppdrag/xsd/printoppdrag-2_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Bestilling" type="Bestilling"/>
	<xs:complexType name="DokumentInfo">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="destinasjon"/>
				<xs:attribute type="xs:string" name="sorteringsfelt"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Kanal">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="behandling"/>
				<xs:attribute type="xs:string" name="type"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="BestillingsInfo">
		<xs:sequence>
			<xs:element type="xs:string" name="KundeOpprettet"/>
			<xs:element type="DokumentInfo" name="DokumentInfo">
				<xs:annotation>
					<xs:documentation>DokumentInfo attributter: destinasjon = "INNLAND", "EUROPA" eller "VERDEN". sorteringsfelt
						= "USORTERT"
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="Kanal" name="Kanal">
				<xs:annotation>
					<xs:documentation>Kanal attributter:
						behandling = "[PRIO]_[KONVTYPE]_[PLEX]",
						[PRIO] = A eller B,
						[KONVTYPE] = X (pakkes i konvolutt med vindu) eller W (pakkes i konvolutt uten vindu),
						[PLEX] = S (simplex) eller D (duplex).
						type = "PRINT"
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="bestillingsId"/>
		<xs:attribute type="xs:string" name="kundeId"/>
		<xs:attribute type="xs:string" name="modus"/>
	</xs:complexType>
	<xs:complexType name="Ressurs">
		<xs:sequence>
			<xs:element type="xs:string" name="Adresse">
				<xs:annotation>
					<xs:documentation>adresse = dokdist.Postadresse.adresselinje1-3 + dokdist.Postadresse.postnummer +
						dokdist.Postadresse.poststed
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Dokument">
		<xs:sequence>
			<xs:element type="xs:string" name="Skattyternummer">
				<xs:annotation>
					<xs:documentation>skatteyternummer = dokdist.DokumentInfo.mottakerId</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="Navn">
				<xs:annotation>
					<xs:documentation>navn = dokdist.DokumentInfo.mottakerNavn</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="Landkode">
				<xs:annotation>
					<xs:documentation>Landkode = postadresse.landkode</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:string" name="Postnummer">
				<xs:annotation>
					<xs:documentation>landkode = dokdist.Postadresse.landkode &lt;Landkode>NO&lt;/Landkode> postnummer =
						dokdist.Postadresse.postnummer &lt;Landkode>NO&lt;/Landkode>
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="dokumentId" use="optional"/>
		<xs:attribute type="xs:string" name="dokumentType" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Mailpiece">
		<xs:sequence>
			<xs:element type="Ressurs" name="Ressurs"/>
			<xs:element type="xs:string" name="Landkode"/>
			<xs:element type="xs:string" name="Postnummer"/>
			<xs:element type="Dokument" name="Dokument" maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>dokumentId = dokdist.DokumentInfo.dokumentId</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:string" name="mailpieceId"/>
	</xs:complexType>
	<xs:complexType name="Bestilling">
		<xs:sequence>
			<xs:element type="BestillingsInfo" name="BestillingsInfo">
				<xs:annotation>
					<xs:documentation>bestillingsId = dokdist.DistribusjonsInfo.distribusjonsId</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="Mailpiece" name="Mailpiece">
				<xs:annotation>
					<xs:documentation>mailpieceId = dokdist.DokumentInfo.dokumentId</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== navikt/dokdistsentralprint/app/src/test/resources/qdist009/bestilling_utenRegoppslag_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Bestilling xsi:noNamespaceSchemaLocation="printoppdrag-2_2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><BestillingsInfo bestillingsId="insertCallIdHere" kundeId="NAV_IKT"><DokumentInfo destinasjon="INNLAND" sorteringsfelt="USORTERT"/><Kanal behandling="B_X_D" type="PRINT"/></BestillingsInfo><Mailpiece mailpieceId="insertCallIdHere"><Ressurs><Adresse>&lt;![CDATA[mottakerNavn&#13;adresselinjeEn&#13;adresselinjeTo&#13;adresselinjeTre&#13;123 poststed&#13;NO]]&gt;</Adresse></Ressurs><Postnummer>123</Postnummer><Dokument dokumentId="dokumentObjektReferanseHoveddok" dokumentType="NAV_STANDARD"><Skattyternummer>mottakerId</Skattyternummer><Navn>&lt;![CDATA[mottakerNavn]]&gt;</Navn><Postnummer>123</Postnummer></Dokument><Dokument dokumentId="dokumentObjektReferanseVedlegg1" dokumentType="NAV_STANDARD"><Skattyternummer>mottakerId</Skattyternummer><Navn>&lt;![CDATA[mottakerNavn]]&gt;</Navn><Postnummer>123</Postnummer></Dokument><Dokument dokumentId="dokumentObjektReferanseVedlegg2" dokumentType="NAV_STANDARD"><Skattyternummer>mottakerId</Skattyternummer><Navn>&lt;![CDATA[mottakerNavn]]&gt;</Navn><Postnummer>123</Postnummer></Dokument></Mailpiece></Bestilling>

=== navikt/dokdistsentralprint/schemas/src/main/resources/no/nav/dokdistsentralprint/printoppdrag/xsd/printoppdrag-2_2.xsd.xml
<?xml version='1.0' encoding='UTF-8'?>
<Bestilling xsi:noNamespaceSchemaLocation="printoppdrag-2_2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- bestillingsId = dokdist.DistribusjonsInfo.distribusjonsId -->
  <BestillingsInfo bestillingsId="unikBestillingsId" kundeId="NAV_IKT" modus="T">
    <KundeOpprettet>2018-11-26</KundeOpprettet>

    <!-- DokumentInfo attributter: destinasjon = "INNLAND", "EUROPA" eller "VERDEN". sorteringsfelt = "USORTERT" -->
    <DokumentInfo destinasjon="INNLAND" sorteringsfelt="USORTERT"/>

    <!-- Kanal attributter:
		behandling = "[PRIO]_[KONVTYPE]_[PLEX]",
			[PRIO] = A eller B,
			[KONVTYPE] = X (pakkes i konvolutt med vindu) eller W (pakkes i konvolutt uten vindu),
			[PLEX] = S (simplex) eller D (duplex).
		type = "PRINT" -->
    <Kanal behandling="A_X_D" type="PRINT"/>

  </BestillingsInfo>

  <!-- mailpieceId = dokdist.DokumentInfo.dokumentId -->
  <Mailpiece mailpieceId="unikMailpieceId">

    <Ressurs>

      <!-- adresse = dokdist.Postadresse.adresselinje1-3 + dokdist.Postadresse.postnummer + dokdist.Postadresse.poststed -->
      <Adresse><![CDATA[Kari Nordmann\rVeien 1\r0712 Moss]]></Adresse>

    </Ressurs>
    <Postnummer>0712</Postnummer>

    <!-- dokumentId = dokdist.DokumentInfo.dokumentId -->
    <Dokument dokumentId="unikHovedDokumentId" dokumentType="NAV_PDFPRINT">

      <!-- skatteyternummer = dokdist.DokumentInfo.mottakerId -->
      <Skattyternummer>mottakerId</Skattyternummer>

      <!-- adresse = dokdist.Postadresse.adresselinje1-3 + dokdist.Postadresse.postnummer + dokdist.Postadresse.poststed -->
      <Adresse><![CDATA[Kari Nordmann\rVeien 1\r0712 Moss]]></Adresse>

      <!-- navn = dokdist.DokumentInfo.mottakerNavn -->
      <Navn><![CDATA[Kari Nordmann]]></Navn>

      <!-- landkode = dokdist.Postadresse.landkode -->
      <!-- <Landkode>NO</Landkode> -->

      <!-- postnummer = dokdist.Postadresse.postnummer -->
      <Postnummer>0712</Postnummer>

    </Dokument>

    <Dokument dokumentId="unikVedleggId" dokumentType="NAV_PDFPRINT">
      <Skattyternummer>mottakerId</Skattyternummer>
      <Adresse><![CDATA[Kari Nordmann\rVeien 1\r0712 Moss]]></Adresse>
      <Navn><![CDATA[Kari Nordmann]]></Navn>
      <!-- <Landkode>NO</Landkode> -->
      <Postnummer>0712</Postnummer>
    </Dokument>

  </Mailpiece>
</Bestilling>

=== navikt/dokdistsentralprint/app/src/test/resources/qdist009/bestilling_xml_uten_skattyternummer.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Bestilling xsi:noNamespaceSchemaLocation="printoppdrag-2_2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><BestillingsInfo bestillingsId="insertCallIdHere" kundeId="NAV_IKT"><DokumentInfo destinasjon="INNLAND" sorteringsfelt="USORTERT"/><Kanal behandling="B_X_D" type="PRINT"/></BestillingsInfo><Mailpiece mailpieceId="insertCallIdHere"><Ressurs><Adresse><![CDATA[mottakerNavn\rlinje1\rlinje2\rlinje3\r3020 Drammen\rTYRKIA]]></Adresse></Ressurs><Landkode>TR</Landkode><Dokument dokumentId="dokumentObjektReferanseHoveddok" dokumentType="NAV_STANDARD"><Navn><![CDATA[mottakerNavn]]></Navn><Landkode>TR</Landkode></Dokument><Dokument dokumentId="dokumentObjektReferanseVedlegg1" dokumentType="NAV_STANDARD"><Navn><![CDATA[mottakerNavn]]></Navn><Landkode>TR</Landkode></Dokument><Dokument dokumentId="dokumentObjektReferanseVedlegg2" dokumentType="NAV_STANDARD"><Navn><![CDATA[mottakerNavn]]></Navn><Landkode>TR</Landkode></Dokument></Mailpiece></Bestilling>

=== navikt/dokdistsentralprint/app/src/test/resources/qdist009/bestilling_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Bestilling xsi:noNamespaceSchemaLocation="printoppdrag-2_2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><BestillingsInfo bestillingsId="insertCallIdHere" kundeId="NAV_IKT"><DokumentInfo destinasjon="INNLAND" sorteringsfelt="USORTERT"/><Kanal behandling="B_X_D" type="PRINT"/></BestillingsInfo><Mailpiece mailpieceId="insertCallIdHere"><Ressurs><Adresse>&lt;![CDATA[mottakerNavn&#13;linje1&#13;linje2&#13;linje3&#13;3020 Drammen&#13;TR]]&gt;</Adresse></Ressurs><Landkode>TR</Landkode><Dokument dokumentId="dokumentObjektReferanseHoveddok" dokumentType="NAV_STANDARD"><Skattyternummer>mottakerId</Skattyternummer><Navn>&lt;![CDATA[mottakerNavn]]&gt;</Navn><Landkode>TR</Landkode></Dokument><Dokument dokumentId="dokumentObjektReferanseVedlegg1" dokumentType="NAV_STANDARD"><Skattyternummer>mottakerId</Skattyternummer><Navn>&lt;![CDATA[mottakerNavn]]&gt;</Navn><Landkode>TR</Landkode></Dokument><Dokument dokumentId="dokumentObjektReferanseVedlegg2" dokumentType="NAV_STANDARD"><Skattyternummer>mottakerId</Skattyternummer><Navn>&lt;![CDATA[mottakerNavn]]&gt;</Navn><Landkode>TR</Landkode></Dokument></Mailpiece></Bestilling>
